# Generated by Django 4.2 on 2023-04-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device_id', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(choices=[('SS', 'Soil Sensor'), ('WS', 'Weather Sensor')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Battery', models.FloatField()),
                ('EC_S1', models.FloatField()),
                ('EC_S2', models.FloatField()),
                ('Moisture_S1_P', models.FloatField()),
                ('Moisture_S2_P', models.FloatField()),
                ('Temperature_S1_P', models.FloatField()),
                ('Temperature_S2_P', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensorproperty')),
            ],
        ),
    ]
