# Generated by Django 4.2 on 2023-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorproperty',
            name='sensor_type',
            field=models.CharField(choices=[('Soil sensor', 'Soil Sensor'), ('Weather sensor', 'Weather Sensor')], max_length=255),
        ),
    ]
