# Generated by Django 4.2 on 2023-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sensor_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Stage', models.CharField(blank=True, max_length=100, null=True)),
                ('Agromet_Advisory', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
