# Generated by Django 4.2 on 2023-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_advisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
